config/routes.rb
ChantalEtHenriRails3::Application.routes.draw do

  resources :tables do
#    resources :guests
  end

  resources :rooms
  
#  resources :liste_mariages

#  resources :statut
#  resources :statuts
  resources :guests
  namespace :admin do
    resources :guests
    resources :photos
    resources :groups do
      resources :emails
    end
  end
  
  #group users
  match '/admin/groups/:group_id/users/:id', to: "admin/groups#add_user" , as: :admin_group_user, via: :put
  match '/admin/groups/:group_id/users/:id', to: "admin/groups#destroy_user" , as: :admin_group_user, via: :delete
  
  namespace :all do
    resources :photos
  end
  
  resources :photos
  match "/all/diaporama", to: "all/photos#diaporama"
  match "/exists/photos", to: "photos#exists"
  match "/toggle/photos", to: "admin/photos#toggle"
  
  resources :infos
  match 'statuts/:id', to: "statuts#edit", as: :edit_statuts
  match 'emails', to: "emails#index", as: :emails, via: :get
  match 'email/:id', to: "emails#show", as: :email, via: :get
  match 'email/:id', to: "emails#destroy", via: :delete
  match 'admin/guests/invite/:id/edit', to: "admin/guests#invite" , via: :get, as: :edit_invite_admin_guest
  match 'admin/guests/invite/:id', to: "admin/guests#update_invite" , as: :invite_admin_guest
  match 'admin/guests/:id/invites', to: "admin/guests#users_invites" , as: :admin_users_invites 
  
  #table guests
  match '/tables/:table_id/guests/:id', to: "tables#add_guest" , as: :table_guest, via: :put
  match '/tables/:table_id/guests/:id', to: "tables#destroy_guest" , as: :table_guest, via: :delete
  
  match "/songs/all", to: "songs#all"
  match "/uploads/all", to: "uploads#all"
  resources :songs
  resources :s3_uploads
  resources :uploads
  resources :users do
    resources :emails
  end
  root to: "sessions#new"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/logout", to: "sessions#destroy", :as => "logout"
  match "/toggle/users/:btn", to: "users#toggle", as: :toggle_users
#  match "/upload", to: "uploads#icreate"
end

app/models/guest.rb
class Guest < User
  attr_accessible :name, :mairie, :diner, :room_id, :myself
  belongs_to :invited_by, :class_name=>"User"
  belongs_to :table
  validates_presence_of :name, :invited_by
  validate :further_validations
  before_save :set_presence
  after_save :save_presence

  def self.search(search)
    if(search)
      where('upper(name) LIKE upper(?)', "%#{search}%")
    else
      scoped
    end
  end
  
  def self.to_install
    cond = ["table_id IS NULL and  diner = ?", true]
    find(:all, :conditions=> cond, :joins => :presence, :order => "name ASC")
  end
  
  def get_statut
  end
  
  def make_guest
  end

  def set_presence
    self.presence ||= self.build_presence
    self.presence.mairie = ( self.mairie=="1" ) if self.mairie
    self.presence.diner = ( self.diner=="1" ) if self.diner
    self.table = nil if !self.presence.diner
    self.presence.save
  end

  def save_presence
    self.presence.save
  end
  
  def further_validations
    return unless room
    disp = self.room.guests - [self]
    self.errors.add(:chambre, "'#{self.room.name}' surchargee ") unless disp.size < self.room.places
    return unless self.table
    disp = self.table.guests - [self]
    self.errors.add(:table, "'#{self.table.name}' surchargee ") unless disp.size < self.table.seats
  end
end

app/controllers/admin/guests_controller.rb
module Admin
class GuestsController < ApplicationController
  before_filter :require_admin
  helper_method :sort_column, :sort_direction

  def index
    guests_index
    respond_to do |format|
      format.html { guests_index }
      format.pdf do
        pdf = GuestsPdf.new(@guests_all)
        file = "Liste Chantal et Henri"
        send_data pdf.render, filename: file,
            type: "application/pdf", disposition: "inline"
      end
    end
  end
  
  def show
    @guest = User.find(params[:id])
  end 
  
  # GET /admin/guests/invite/1/edit
  def invite
    @guest = Guest.find_by_id(params[:id])
  end
  
  # PUT /admin/guests/invite/1
  def update_invite
    @guest = Guest.find(params[:id])
    @guest.invited_by_id = params[:guest][:invited_by_id]
    respond_to do |format|
      if (@guest.save)
        format.html do
          guests_index
          render action: "index"
        end
        format.json { head :no_content }
      else
        msg = "Requete invalide: #{@guest.errors.full_messages}"
        format.html { redirect_to guests_url, alert: msg }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end 
  
  #get /admin/guests/id/invites
  def users_invites
    @guests=User.find(params[:id]).guests.page(params[:page]).per(10)
    render action: "index"
  end
  
  # GET /users/1/edit
  def edit
    @guest = Guest.find_by_id(params[:id])
  end
  
  # PUT /users/1
  # PUT /users/1.json
  def update
    @guest = Guest.find(params[:id])
    respond_to do |format|
      if (@guest.update_attributes(params[:guest]))
        format.html do
          guests_index
          render action: "index"
        end
        format.json { head :no_content }
      else
        msg = "Requete invalide: #{@guest.errors.full_messages}"
        format.html { redirect_to guests_url, alert: msg }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @guest = Guest.find(params[:id])
    respond_to do |format|
        @guest.destroy
        format.html { redirect_to admin_guests_url }
        format.json { head :no_content }
    end
  end

private

  def guests_index
    scope = params[:join] ? Guest.joins(params[:join]).order("#{params[:join]}.#{params[:sort]}") : Guest.order(sort_column + " " + sort_direction)
    @guests_all = scope.search(params[:search])
    @guests=scope.search(params[:search]).page(params[:page]).per(10)
  end
  
  def sort_column
    params[:sort] || "name"
  end

  def sort_direction
    params[:direction] || "asc"
  end

end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  def index
  end

  def new
    @guest = Guest.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guest }
    end
  end
  
  def create
    @guest = current_user.guests.build(params[:guest])
#    raise 'params[:guest]='+params[:guest].inspect
    respond_to do |format|
      if @guest.save
        @user=@guest
#        format.html { redirect_to @guest, notice: 'Invite enregistre' }
        format.html do
          render action: "index"
        end
        format.json { render json: @guest, status: :created, location: @guest }
      else
        format.html { render action: "new" }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
    @guest = params[:id].to_i == current_user.id ? current_user : current_user.guests.find(params[:id])
  end
  
  # GET /users/1/edit
  def edit
    @guest = current_user.guests.find_by_id(params[:id])
    @guest ||=current_user
  end
  
  # PUT /users/1
  # PUT /users/1.json
  def update
    @guest = params[:id].to_i == current_user.id ? current_user : current_user.guests.find(params[:id])
    respond_to do |format|
      if (@guest.update_attributes(params[:guest]))
        format.html do
          render action: "index"
        end
        format.json { head :no_content }
      else
        msg = "Requete invalide: #{@guest.errors.full_messages}"
        format.html { redirect_to guests_url, alert: msg }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @guest = current_user.guests.find(params[:id])
    respond_to do |format|
        @guest.destroy
        format.html { redirect_to guests_url }
        format.json { head :no_content }
    end
  end

end

app/views/admin/guests/_form.html.erb
<%= form_for @guest, :url=>admin_guest_path, :html => { :class => 'form-horizontal' } do |f| %>
  <% @guest.mairie = true if @guest.at_mairie? %>
  <% @guest.diner = true if @guest.at_diner? %>
  <div class="control-group">
    <%= f.label "Nom", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'input-xlarge' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Presence", :class => 'control-label' %>
    <div class="controls">
      <label class="checkbox">
      	<%= f.check_box :mairie, :class => 'checkbox' %>
      	&agrave; la mairie
      </label>
      <label class="checkbox">
      	<%= f.check_box :diner, :class => 'checkbox' %>
      	&agrave; la soir&eacute;e
      </label>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Hebergement", :class => 'control-label' %>
    <div class="controls">
    	<%= f.select("room_id", @guest.invited_by.rooms.collect {|p| [ p.full_name, p.id ] }, {:include_blank => 'None'})%>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to "Invité par",
                edit_invite_admin_guest_path, :class => 'btn btn-warning' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_guests_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/guests/edit.html.erb
<%- model_class = @guest.class -%>
<h3><%= "#{@guest.name}" %></h3>
<p>                           
<%= render :partial => 'form' %>

app/views/admin/guests/index.html.erb
<%- model_class = User.new.class -%>

<%= paginate @guests %>

<h2><%= link_to "Les invités", admin_guests_path%></h2>
<p></p>
<%= form_tag admin_guests_path, method: :get do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Chercher", name: nil %>
  </p>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable :name %></th>
      <th><%= "Invité par" %></th>
      <th>Mairie</th>
      <th>Diner</th>
      <th>Chambre</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
    <tr>
      <th></th>
      <th></th>
      <th><%= Presence.count(:conditions=>["mairie = ?", true]) %></th>
      <th><%= Presence.count(:conditions=>["diner = ?", true]) %></th>
      <th><%= Room.count %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% for guest in @guests %>
      <tr>
        <td><%= link_to guest.name, admin_guest_path(guest) %></td>
        <td>
	      <% if(guest.invited_by)%>
            <%= link_to guest.invited_by.name,
                      admin_users_invites_path(guest.invited_by) %>
	      <% else %>
	        ""
	      <% end %>
	    </td>
        <td><% if guest.at_mairie?%><i class="icon-ok"/><% end %></td>
        <td><% if guest.at_diner?%><i class="icon-ok"/><% end %></td>
        <td><% if guest.room %><%= guest.room.name %><% end %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_guest_path(guest), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_guest_path(guest),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>      

<p><%= link_to "Imprimer la liste (PDF)", admin_guests_path(format: "pdf") %></p>

app/views/admin/guests/invite.html.erb
<%- model_class = @guest.class -%>
<h3><%= "#{@guest.name}" %></h3>
<p>                           
	<%= form_for @guest, :url=> invite_admin_guest_path, :html => { :class => 'form-horizontal' } do |f| %>
	  <div class="control-group">
	    <%= f.label "Invité par", :class => 'control-label' %>
	    <div class="controls">
	    	<%= f.select("invited_by_id", User.all.collect {|p| [ p.name, p.id ] })%>
	    </div>
	  </div>

	  <div class="form-actions">
	    <%= f.submit nil, :class => 'btn btn-primary' %>
	    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	                edit_admin_guest_path(@guest), :class => 'btn' %>
	  </div>
	<% end %>

app/views/admin/guests/show.html.erb
<%- model_class = @guest.class -%>
<h2>Profil de <%= @guest.name%></h2>
<p>
  <strong>Invité par:</strong><br>
  <%= @guest.invited_by.name%>
</p>
<% if @guest.presence.mairie %>
<p>
  <strong>Présent a la mairie</strong><br>
</p>
<% end %>
<% if @guest.presence.diner %>
<p>
  <strong>Présent a la soirée</strong><br>
</p>
<% end %>
<% if @guest.table %>
<p>
  <strong><%= @guest.table.name %></strong><br>
</p>
<% end %>



<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_guests_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_guest_path(@guest),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>