config/routes.rb
ChantalEtHenriRails3::Application.routes.draw do

  resources :tables do
#    resources :guests
  end

  resources :rooms
  
#  resources :liste_mariages

#  resources :statut
#  resources :statuts
  resources :guests
  namespace :admin do
    resources :guests
    resources :photos
    resources :groups do
      resources :emails
    end
  end
  
  #group users
  match '/admin/groups/:group_id/users/:id', to: "admin/groups#add_user" , as: :admin_group_user, via: :put
  match '/admin/groups/:group_id/users/:id', to: "admin/groups#destroy_user" , as: :admin_group_user, via: :delete
  
  namespace :all do
    resources :photos
  end
  
  resources :photos
  match "/all/diaporama", to: "all/photos#diaporama"
  match "/exists/photos", to: "photos#exists"
  match "/toggle/photos", to: "admin/photos#toggle"
  
  resources :infos
  match 'statuts/:id', to: "statuts#edit", as: :edit_statuts
  match 'emails', to: "emails#index", as: :emails, via: :get
  match 'email/:id', to: "emails#show", as: :email, via: :get
  match 'email/:id', to: "emails#destroy", via: :delete
  match 'admin/guests/invite/:id/edit', to: "admin/guests#invite" , via: :get, as: :edit_invite_admin_guest
  match 'admin/guests/invite/:id', to: "admin/guests#update_invite" , as: :invite_admin_guest
  match 'admin/guests/:id/invites', to: "admin/guests#users_invites" , as: :admin_users_invites 
  
  #table guests
  match '/tables/:table_id/guests/:id', to: "tables#add_guest" , as: :table_guest, via: :put
  match '/tables/:table_id/guests/:id', to: "tables#destroy_guest" , as: :table_guest, via: :delete
  
  match "/songs/all", to: "songs#all"
  match "/uploads/all", to: "uploads#all"
  resources :songs
  resources :s3_uploads
  resources :uploads
  resources :users do
    resources :emails
  end
  root to: "sessions#new"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/logout", to: "sessions#destroy", :as => "logout"
  match "/toggle/users/:btn", to: "users#toggle", as: :toggle_users
#  match "/upload", to: "uploads#icreate"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :admin, :activated
  attr_accessor :x_activated, :mairie, :diner
  has_many :category_users, :dependent => :destroy
  has_one  :statut, :dependent => :destroy
  has_many :photos
  has_many :presences, :through => :guests do
    def at(lieu)
      find(:all, :conditions=>"\"presences\".\"#{lieu}\" IS TRUE")
    end
  end
  has_one  :presence, :dependent => :destroy
  has_many :songs, :through => :category_users
  has_many :emails, :as=>:to
  has_many :rooms do
    def available
      list =[]
      all.each do |r|
        list << r if r.guests.size < r.places
      end
      list
    end
  end
  has_many :singles, :class_name=>"Room::Single"
  has_many :doubles, :class_name=>"Room::Double"
  belongs_to :room
  has_many :guests, :foreign_key=>:invited_by_id, :dependent => :destroy do
    def myself
      find(:first, :conditions=>'myself IS TRUE')      
    end
  end
  has_many :uploads, :through => :songs
  has_many :direct_uploads, :class_name => "Upload", :foreign_key=>:added_by_id
  after_initialize :set_initial_values
  
  validates_presence_of :name
  
  def self.no_guests(activated=nil)
    if activated.nil?
      cond = "type IS NULL"
    elsif activated
      cond = ["type IS NULL AND activated = ?", true]
    else
      cond = ["type IS NULL AND activated IS NULL OR activated = ?", false]
    end
    find(:all, :conditions=>cond)
  end

  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.email = auth["info"]["email"]
      user.name = auth["info"]["name"]
      user.nickname = auth["info"]["nickname"]
      user.first_name = auth["info"]["first_name"]
      user.last_name = auth["info"]["last_name"]
      user.image = auth["info"]["image"]
      user.location = auth["info"]["location"]
    end
  end
  
  def newly_activated?
    self.activated && !self.x_activated
  end
  
  def self.fake(email=nil)
    user = User.new
    fn = Faker::Name
    user.name = fn.name; user.first_name = fn.first_name; user.last_name = fn.last_name
    user.email = email
    user.email ||= Faker::Internet.email(user.name)
    puts UserMailer.registration_confirmation(user).deliver
    user
  end
  
  def get_statut
    self.statut ||= self.create_statut
  end
  
  def at_mairie?
    return false unless presence
    presence.mairie
  end
  
  def at_diner?
    return false unless presence
    presence.diner
  end
  
  def receivers
    [self.email]
  end
  
private
  
  def set_initial_values
    self.x_activated = self.activated
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_admin

  def index
    @users = current_list   
  end
  
  def show
    @user = User.find_by_id(params[:id])
  end
  
  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end
  
  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if (@user != current_user && @user.update_attributes(params[:user]))
        if @user.newly_activated?
          UserMailer.registration_confirmation(@user).deliver
        end
        format.html do
          @users = current_list
          render action: "index"
        end
        format.json { head :no_content }
      else
        msg = @user == current_user ? 'Impossible de modifier ses propres parametres' : 'Requete invalide'
        format.html { redirect_to users_url, alert: msg }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
    
  def toggle
    session[:usr_btn] = params[:btn].to_i
    redirect_to users_url
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    respond_to do |format|
      if(@user == current_user)
        format.html { redirect_to users_url, alert: "Impossible de s'auto supprimer! (n'importe quoi !...)" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      else
        @user.destroy
        format.html { redirect_to users_url }
        format.json { head :no_content }
      end
    end
  end

private
  def current_list
    @btn = [false, false, false]
    session[:usr_btn] ||= 1
    @btn[session[:usr_btn]]=true
    case session[:usr_btn]
    when 0
      User.no_guests
    when 1
      User.no_guests(false)
    else
      User.no_guests(true)
    end
    
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label "Activé", :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :activated, :class => 'checkbox' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Administrateur", :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :admin, :class => 'checkbox' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = @user.class -%>
<h2><%= "#{@user.name} (#{@user.provider})" %></h2>
<p>                           
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<div class="span12 columns">
<%- model_class = User.new.class -%>
<h2>
  Les utilisateurs
  <div class="btn-group">
    <%= link_to "Tous", toggle_users_url(0), :class => 'btn btn-primary', :disabled => @btn[0] %>
    <%= link_to "Non autorisés", toggle_users_url(1), :class => 'btn btn-primary', :disabled => @btn[1] %>
    <%= link_to "Autorisés", toggle_users_url(2), :class => 'btn btn-success', :disabled => @btn[2] %>
  </div>
</h2><p></p>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:provider) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th>Statut</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.provider %></td>
        <td><%= user.email %></td>
        <% if user.activated %>
        	<% if user.admin %>
        		<td><span class="label label-info">Administrateur</span></td>
        	<% else %>
        		<td><code>Actif</code></td>
        	<% end %>
        <% else %>
        	<% if user.is_a?(Guest)%>
        		<td><span class="label">invité</span></td>
        	<% else %>
        		<td>Non activé</td>
        	<% end %>
        <% end %>
        <td>
          <% unless user.is_a?(Guest) %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.email', :default => t("helpers.links.email")),
                      new_user_email_path(user), :class => 'btn btn-mini' %>
          <% end %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>