config/routes.rb
ChantalEtHenriRails3::Application.routes.draw do

  resources :tables do
#    resources :guests
  end

  resources :rooms
  
#  resources :liste_mariages

#  resources :statut
#  resources :statuts
  resources :guests
  namespace :admin do
    resources :guests
    resources :photos
    resources :groups do
      resources :emails
    end
  end
  
  #group users
  match '/admin/groups/:group_id/users/:id', to: "admin/groups#add_user" , as: :admin_group_user, via: :put
  match '/admin/groups/:group_id/users/:id', to: "admin/groups#destroy_user" , as: :admin_group_user, via: :delete
  
  namespace :all do
    resources :photos
  end
  
  resources :photos
  match "/all/diaporama", to: "all/photos#diaporama"
  match "/exists/photos", to: "photos#exists"
  match "/toggle/photos", to: "admin/photos#toggle"
  
  resources :infos
  match 'statuts/:id', to: "statuts#edit", as: :edit_statuts
  match 'emails', to: "emails#index", as: :emails, via: :get
  match 'email/:id', to: "emails#show", as: :email, via: :get
  match 'email/:id', to: "emails#destroy", via: :delete
  match 'admin/guests/invite/:id/edit', to: "admin/guests#invite" , via: :get, as: :edit_invite_admin_guest
  match 'admin/guests/invite/:id', to: "admin/guests#update_invite" , as: :invite_admin_guest
  match 'admin/guests/:id/invites', to: "admin/guests#users_invites" , as: :admin_users_invites 
  
  #table guests
  match '/tables/:table_id/guests/:id', to: "tables#add_guest" , as: :table_guest, via: :put
  match '/tables/:table_id/guests/:id', to: "tables#destroy_guest" , as: :table_guest, via: :delete
  
  match "/songs/all", to: "songs#all"
  match "/uploads/all", to: "uploads#all"
  resources :songs
  resources :s3_uploads
  resources :uploads
  resources :users do
    resources :emails
  end
  root to: "sessions#new"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/logout", to: "sessions#destroy", :as => "logout"
  match "/toggle/users/:btn", to: "users#toggle", as: :toggle_users
#  match "/upload", to: "uploads#icreate"
end

app/models/info.rb
class Info < ActiveRecord::Base
  default_scope :order => "updated_at DESC"
  attr_accessible :author_id, :subject, :text
  belongs_to :author, :class_name=>"User"
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_filter :require_admin
  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @infos }
    end
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
    @info = Info.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/new
  # GET /infos/new.json
  def new
    @info = Info.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/1/edit
  def edit
    @info = Info.find(params[:id])
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(params[:info])
    @info.author = current_user
    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render json: @info, status: :created, location: @info }
      else
        format.html { render action: "new" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /infos/1
  # PUT /infos/1.json
  def update
    @info = Info.find(params[:id])

    respond_to do |format|
      if @info.update_attributes(params[:info])
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info = Info.find(params[:id])
    @info.destroy

    respond_to do |format|
      format.html { redirect_to infos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.erb
<%= form_for @info, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :subject, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subject, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :text, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                infos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<%- model_class = @info.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/infos/index.html.erb
<%- model_class = Info.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:subject) %></th>
      <th><%= model_class.human_attribute_name(:author) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td><%= link_to info.id, info_path(info) %></td>
        <td><%= info.subject %></td>
        <td><%= info.author.name if info.author %></td>
        <td><%=l info.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_info_path(info), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      info_path(info),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_info_path,
            :class => 'btn btn-primary' %>

app/views/infos/new.html.erb
<%- model_class = @info.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/infos/show.html.erb
<%- model_class = @info.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:subject) %>:</strong><br>
  <%= @info.subject %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:text) %>:</strong><br>
  <%= @info.text %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:author_id) %>:</strong><br>
  <%= @info.author.name if @info.author %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              infos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_info_path(@info), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              info_path(@info),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>